#!/bin/bash

clear

fun_bar () {

comando[0]="$1"

comando[1]="$2"

 (

[[ -e $HOME/fim ]] && rm $HOME/fim

${comando[0]} > /dev/null 2>&1

${comando[1]} > /dev/null 2>&1

touch $HOME/fim

 ) > /dev/null 2>&1 &

 tput civis

echo -ne "   \033[1;33mWAIT \033[1;37m- \033[1;33m["

while true; do

   for((i=0; i<18; i++)); do

   echo -ne "\033[1;31m#"

   sleep 0.1s

   done

   [[ -e $HOME/fim ]] && rm $HOME/fim && break

   echo -e "\033[1;33m]"

   sleep 1s

   tput cuu1

   tput dl1

   echo -ne "   \033[1;33mWAIT \033[1;37m- \033[1;33m["

done

echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"

tput cnorm

}

echo " "

fun_atts () {

  [[ -e /home/versao ]] && rm /home/versao

  [[ -e /tmp/att ]] && rm /tmp/att

	timeout 60 wget -c -P /home https://raw.githubusercontent.com/mooa322/SSHPLUS/main/Install/versao

	[[ -f "/home/versao" ]] && mv /home/versao /tmp/att

	[[ ! -e /bin/versao ]] && rm -rf /bin/menu

} > /dev/null 2>&1

echo -e "                              \033[1;31mBy kiritosshxd\033[1;36m"

echo -e "   SSHPlus" | figlet

echo " "

echo -e "   \033[1;32mCHECKING FOR AVAILABLE UPDATES\033[0m\n"

fun_bar 'fun_atts'

[[ ! -f "/tmp/att" ]] && {

	echo -e "\n\033[1;31m ERROR CONNECTING TO THE SERVER\n"

	echo -ne "\033[1;31m ENTER \033[1;33mto return to the \033[1;32mMENU!\033[0m"; read

	menu

}

echo " "

vrs1=$(sed -n '1 p' /bin/versao| sed -e 's/[^0-9]//ig')

vrs2=$(sed -n '1 p' /tmp/att | sed -e 's/[^0-9]//ig')

[[ "$vrs1" == "$vrs2" ]] && {

  echo -e " \033[1;36m     THE SCRIPT IS ALREADY UP TO DATE!\033[1;32m\n"

  rm /tmp/att > /dev/null 2>&1

  echo -e " \033[1;33m MORE INFORMATION \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@OMentalista\n"

  echo -ne " \033[1;31m ENTER \033[1;33mto return to the \033[1;32mMENU!\033[0m"; read

  menu

} || {

  echo -e "  \033[1;36mA NEW UPDATE IS AVAILABLE!\033[1;33m\n"

  echo -e "  \033[1;33mMORE INFORMATION \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@OMentalista\n"

  echo -e "  \033[1;32mUPDATE DETAILS:\033[0m\n"

  while read linha; do

    echo -e "  \033[1;37m- \033[1;33m$linha"

  done < "/tmp/att"

  echo " "

  echo -ne "  \033[1;32mDO YOU WANT TO UPDATE \033[1;31m? \033[1;33m[y/n]:\033[1;37m "; read res

  if [[ "$res" = s || "$res" = S || "$res" = y || "$res" = Y ]];then

    echo -e "\n\033[1;32m  STARTING UPDATE..."

    sleep 3

    timeout 60 wget https://raw.githubusercontent.com/mooa322/SSHPLUS/main/Plus > /dev/null 2>&1

    chmod +x Plus

    ./Plus

    clear

    echo -e "\033[1;32mSCRIPT SUCCESSFULLY UPDATED\033[0m\n"

    rm /tmp/att > /dev/null 2>&1

    echo -ne "\033[1;31mENTER \033[1;33mto return to the \033[1;32mMENU!\033[0m"; read

    menu

  else

    menu

  fi

}
