#!/bin/bash
[[ $(screen -list| grep -c 'bot_teste') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     ACTIVATE SSH TEST BOT     \E[0m"
    echo ""
    echo -ne "\n\033[1;32mENTER THE TOKEN\033[1;37m: "; read token
    cd $HOME/BOT
    screen -dmS bot_teste ./botssh $token > /dev/null 2>&1
    clear && echo "BOT ACTIVATED"
} || {
    screen -r -S "bot_teste" -X quit
    clear && echo "BOT DEACTIVATED"
}